# Generated by Django 4.2.2 on 2023-06-08 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.DateTimeField(max_length=300, null=True)),
                ('votes', models.IntegerField(default=0, null=True)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questions')),
            ],
        ),
    ]
